// Shape of src/shorts-data.ts (generated by tools/build_shorts.py). All times are timeline FRAMES
// unless the name says "Sec". Crop rects are in SOURCE pixels of the proxy (same size as the VOD).
export type Rect = [number, number, number, number]; // x, y, w, h (source px)

export type Layout = 'stack' | 'face' | 'game';

export type Seg = {
  start: number; // timeline frame
  len: number;
  src?: string; // proxy under public/ (defaults to the short's src)
  fromSec: number; // in-point inside the proxy file, seconds
  layout: Layout;
  gameX?: number; // horizontal focus of the game crop, 0-1 (0.5 = crosshair)
  speed?: number; // 0 = freeze frame (outro)
  blur?: Rect[]; // privacy boxes for this segment (source px)
  blurGame?: boolean; // blur the whole game panel (menus, scoreboards, desktop)
};

export type Word = {start: number; len: number; text: string; hl?: boolean};
export type Cap = {start: number; len: number; words: Word[]};

export type Fx = {at: number; kind: 'punch' | 'shake' | 'flash' | 'freeze'; len: number; text?: string; strength?: number};

export type StreamShortData = {
  id: string;
  fps: number;
  total: number;
  src: string; // proxy under public/
  srcW: number;
  srcH: number;
  cam: Rect; // facecam box in the source
  camBlur?: Rect[]; // boxes inside the cam to blur (e.g. overlays)
  gameBlur?: Rect[]; // boxes in the game area to blur (names, chat)
  segs: Seg[];
  caps: Cap[];
  fx: Fx[];
  hook: {text: string; sub?: string; len: number};
  tag?: string; // small top-left label ("CS2", "APEX")
  outro?: {text: string; len: number};
};
