#!/usr/bin/env bash
# Scaffold a stream-highlights project on top of yt-video-creator's template.
#
# usage: setup_stream.sh <vod_file> [project_name]
#   -> <vod_dir>/<project_name>/  (default: shorts-video)
#
# What it adds to the base scaffold (setup_project.sh: Remotion, source/ links, media.json, plan.json):
#   source/vod.<ext>        short alias for the (usually 60-char) VOD file name
#   src/stream/*            StreamShort component + types; src/Root.tsx registering one comp per short
#   src/shorts-data.ts      generated by build_shorts.py (empty until the first build)
#   shorts.json             from the example — REPLACE its shorts; set "cam" from detect_cam.py
#   render-shorts.sh        renders every (or chosen) short through versioned render.mjs
#   analysis/               where vod_audio.py / skim_vod.py / find_moments.py write
#   npm scripts: build:shorts, render:shorts
set -euo pipefail
VOD="$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
NAME="${2:-shorts-video}"
HERE="$(cd "$(dirname "$0")" && pwd -P)"
SKILL="$(cd "$HERE/.." && pwd -P)"
BASE="$(cd "$SKILL/.." && pwd -P)"
[ -f "$BASE/scripts/setup_project.sh" ] || BASE="$HOME/.claude/skills/yt-video-creator"

bash "$BASE/scripts/setup_project.sh" "$(dirname "$VOD")" "$NAME"
PROJ="$(dirname "$VOD")/$NAME"
cd "$PROJ"

stem="$(basename "$VOD")"; stem="${stem%.*}"; ext="$(echo "${VOD##*.}" | tr 'A-Z' 'a-z')"
id="$(echo "$stem" | tr ' ()' '_--')"
ln -sfn "$id.$ext" "source/vod.$ext"

mkdir -p src/stream analysis transcripts
cp "$SKILL/assets/stream/StreamShort.tsx" "$SKILL/assets/stream/types.ts" src/stream/
cp "$SKILL/assets/stream/Root.tsx" src/Root.tsx
cp "$SKILL/assets/stream/shorts-data.ts" src/shorts-data.ts
cp "$SKILL/assets/stream/render-shorts.sh" render-shorts.sh
[ -e shorts.json ] || sed "s|\"vod.mp4\"|\"vod.$ext\"|" "$SKILL/assets/stream/shorts.example.json" > shorts.json
echo "[]" > shorts-data.json
npm pkg set "scripts.build:shorts=python3 \"$SKILL/scripts/build_shorts.py\" --project ."
npm pkg set "scripts.render:shorts=./render-shorts.sh"
printf "analysis\nshorts-data.json\n" >> .gitignore
npx tsc -p . >/dev/null && echo "typecheck ok"
echo
echo "Stream project ready: $PROJ"
echo "Next: VENV_PY=\$(bash $BASE/scripts/setup_speech.sh); \$VENV_PY $SKILL/scripts/vod_audio.py source/vod.$ext --project ."
