// GENERATED by build_edit.py from plan.json. Edit plan.json and re-run; don't edit this file.
import type {LongData, ShortData, ThumbData} from './types';

export const LONG: LongData | null = null;

export const SHORT: ShortData | null = null;

export const THUMB: ThumbData | null = null;
