// Shape of src/edit-data.ts (generated by build_edit.py). All positions are in frames.
export type Sub = {from: number; len: number; text: string}; // shot-local frames
export type Rect = [number, number, number, number]; // x, y, w, h in % of frame

export type Shot = {
  start: number;
  len: number;
  src?: string; // under public/ (video)
  from?: number; // in-point inside `src`, seconds
  photo?: string; // under public/ (still)
  speed?: number;
  vol?: number; // source audio volume; absent = muted
  music?: boolean;
  subs?: Sub[];
  x?: number; // crop focus %, for fit 'cover'
  y?: number;
  fit?: 'cover' | 'blur';
  blur?: Rect[]; // privacy blur boxes
  chip?: {big: string; small: string};
  srcClip?: string; // provenance, not rendered
};

export type CounterSpec = {from: number; to: number; max?: number; format?: 'min' | 'int' | 'dec1'; label: string};

export type Section = {start: number; len: number; title?: string; sub?: string; step?: number; counter?: CounterSpec; shots: Shot[]};

export type LongData = {
  fps: number;
  total: number;
  captions: 'top' | 'bottom';
  intro?: {kicker?: string; title: string; subtitle?: string} | null;
  sections: Section[];
  listCard?: {start: number; len: number; title: string; rows: [string, string][]; photo?: string} | null;
  outro?: {start: number; len: number; photo?: string; columns: {title: string; numbered?: boolean; items: string[]}[]};
  credits?: {start: number; len: number; lines: [string, string][]; teaser?: string; photo?: string};
  post?: {start: number; len: number; shots: Shot[]};
  music: {file: string; volume: number; mode: 'bed' | 'broll'; runs: {start: number; len: number; songFrom: number}[]; fadeIn: number; fadeOut: number} | null;
};

export type ShortData = {
  fps: number;
  total: number;
  sections: {start: number; len: number; big?: string; small?: string; shots: Shot[]}[];
  end: {start: number; len: number; photo?: string; big?: string; small?: string};
  music: {file: string; startSec: number; volume: number} | null;
};

// YouTube thumbnail (1280x720). Panels are full-canvas images clipped into a diagonal split
// (1 panel = full bleed). cx/cy = focus point (0-1) that zoom scales around; dx/dy shift in %.
export type ThumbPanel = {src: string; cx?: number; cy?: number; zoom?: number; dx?: number; dy?: number};
export type ThumbData = {panels: ThumbPanel[]; title: string; badge?: string; kicker?: string};
